spring:
  profiles:
    active: dev
  devtools:
    restart:
      additional-paths: resources/**,static/**,templates/**
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/authority?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    filters: stat,wall,slf4j
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
mybatis:
  mapper-locations: classpath:/mybatis-mappers/*
  type-aliases-package: com.sxbang.springbootauthority.model
  configuration:
    map-underscore-to-camel-case: true

api-url: /api